import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import MyCartProvider from "./Providers/MyCartProvider";
import ShoppingCartModal from "./Components/ShoppingCartModal";
import MySessionProvider from "./Providers/MySessionProvider";

const inter = Inter({ subsets: ["latin"] });

const pagesToAvoid: string[] = [
  "auth/login",
]

export const metadata: Metadata = {
  title: "Sushi X",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <MySessionProvider>
          <MyCartProvider>
            <Navbar  />
            <ShoppingCartModal />
            {children}
            <Footer />
          </MyCartProvider>
        </MySessionProvider>
      </body>
    </html>
  );
}
